# Generated by Django 3.2 on 2021-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('status', models.CharField(max_length=12)),
                ('failures', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerScanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='machines.scan')),
                ('user_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanComments', to='login.secureualluser')),
            ],
        ),
    ]
