services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=secureuall
            - POSTGRES_USER=frontend
            - POSTGRES_PASSWORD=abc

    frontend:
        build:
            dockerfile: docker/frontend/Dockerfile
            context: ../
        ports:
            - 9000:9000
        environment:
            - RUNNING_MODE=production
            - DB_NAME=secureuall
            - DB_USER=frontend
            - DB_PASSWORD=abc
            - DB_HOST=localhost
            - DB_PORT=5432
        depends_on:
            - "db"

    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./interface/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - "frontend"