services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432 # TODO! Remove on production!
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=secureuall
            - POSTGRES_USER=frontend
            - POSTGRES_PASSWORD=abc


    frontend:
        build:
            dockerfile: docker/frontend/Dockerfile
            context: ../
        environment:
            - RUNNING_MODE=docker
            - DB_NAME=secureuall
            - DB_USER=frontend
            - DB_PASSWORD=abc
            - DB_HOST=db
            - DB_PORT=5432
            - DJANGO_SUPERUSERS=["gmatos.ferreira@ua.pt", "margarida.martins@ua.pt", "isadora.fl@ua.pt", "pedro.bas@ua.pt", "eduardosantoshf@ua.pt", "moraisandre@ua.pt"]
        volumes:
            - ../secureuall:/app
        depends_on:
            - "db"


    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ../secureuall/static:/var/www/html/static # Django static files
            - ./interface/nginx.conf:/etc/nginx/nginx.conf # nginx configuration
        depends_on:
            - "frontend"

networks:
    default:
        external:
            name: rede
