services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432 # TODO! Remove on production!
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=secureuall
            - POSTGRES_USER=frontend
            - POSTGRES_PASSWORD=abc


    frontend:
        build:
            dockerfile: docker/frontend/Dockerfile
            context: ../
        environment:
            - RUNNING_MODE=production
            - DB_NAME=secureuall
            - DB_USER=frontend
            - DB_PASSWORD=abc
            - DB_HOST=db
            - DB_PORT=5432
            - EMAIL_HOST=exchange.ua.pt
            - EMAIL_PORT=25
            - EMAIL_USER=deti-vuln-mon@ua.pt
            - EMAIL_PASSWORD=eGdgtY56eF#bve8AxeFe
            - DJANGO_SUPERUSERS=["gmatos.ferreira@ua.pt", "margarida.martins@ua.pt", "isadora.fl@ua.pt", "pedro.bas@ua.pt", "eduardosantoshf@ua.pt", "moraisandre@ua.pt"]
        volumes:
            - ./data/djangostaticfiles:/app/static # Static files for nginx to serve
        depends_on:
            - "db"


    nginx:
        image: nginx
        ports:
            - 80:80 # Production
            - 443:443 # SSL
        volumes:
            - ./data/djangostaticfiles:/var/www/html/static # Django static files
            - ./interface/nginx.conf:/etc/nginx/nginx.conf # nginx configuration
            - ./interface/sslCerts/ssl:/etc/ssl # SSL certificates
            - ./interface/sslCerts/snippets:/etc/nginx/snippets # SSL snippets
        depends_on:
            - "frontend"

networks:
    default:
        external:
            name: rede
