# Generated by Django 3.2 on 2021-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('os', models.CharField(max_length=20)),
                ('risk', models.IntegerField()),
                ('scanLevel', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MachineDNS',
            fields=[
                ('dns', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MachinePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=24)),
                ('version', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MachineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.IntegerField()),
                ('type', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=12)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login.secureualluser')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='machines.vulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationEmail', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=256)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='machines.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='login.secureualluser')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=15)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='machines.machine')),
            ],
        ),
    ]
