# Generated by Django 3.2 on 2021-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('login', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='machineuser',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='machineuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='login.secureualluser'),
        ),
        migrations.AddField(
            model_name='machineuser',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machineUsers', to='login.usertype'),
        ),
        migrations.AlterUniqueTogether(
            name='machineservice',
            unique_together={('service', 'version')},
        ),
        migrations.AddField(
            model_name='machineport',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='machineport',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machineservice'),
        ),
        migrations.AddField(
            model_name='machinedns',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DNS', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='log',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='log',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workers.worker'),
        ),
        migrations.AlterUniqueTogether(
            name='machineuser',
            unique_together={('user', 'machine')},
        ),
        migrations.AlterUniqueTogether(
            name='machineport',
            unique_together={('machine', 'port')},
        ),
    ]
