# Generated by Django 3.2 on 2021-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210505_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
