# This is a basic workflow to help you get started with Actions

name: CDVM

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'deploy'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: label-vm # Using linux machine

    steps:
      - uses: actions/checkout@v2 # Checkout the code

      - name: Validate docker
        working-directory: docker
        run: docker-compose config

      - name: Create network
        working-directory: docker
        run: docker network ls |grep rede > /dev/null || docker network create rede

      - name: Start docker
        working-directory: docker
        run: docker-compose up -d --build

      - name: Check that containers are running
        working-directory: docker
        run: docker-compose ps
